server:
  port: 8080
    
eureka:
  instance:
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    enabled: true
    eureka-service-url-poll-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 2
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
